# Generated by Django 2.0 on 2020-10-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicecreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=64, null=True, verbose_name='last name')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
    ]
